[package]
name = "rust-kernel"
version = "0.1.0"
edition = "2021"
authors = ["Zilberguy ori.zilberman1@gmail.com", "Zikithezikit zikithezikit@gmail.com"]
description = "A simple x86_64 kernel written in Rust."


[dependencies]
x86_64 = "0.15.4"
spin = "0.10.0"
pc-keyboard = "0.8.0"
pic8259 = "0.11.0"
heapless = "0.9.2"
lazy_static = { version = "1.5", features = ["spin_no_std"] }
paste = "1.0.15"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[features]
default = []

[lib]
path = "src/main.rs"
crate-type = ["staticlib"]

[build-dependencies]

[workspace]
